// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hotel.data;

public partial class B01BookingDetail
{
    public long BookingId { get; set; }

    public string DocketeNo { get; set; }

    public string BillNo { get; set; }

    public DateTime BookingDate { get; set; }

    public DateOnly? CheckInDate { get; set; }

    public DateOnly? CheckOutDate { get; set; }

    public DateTime? CheckInDate1 { get; set; }

    public DateTime? CheckOutDate1 { get; set; }

    public string HotelId { get; set; }

    public decimal? NetPayable { get; set; }

    public decimal? PaidAmount { get; set; }

    public decimal? DueAmount { get; set; }

    public string Status { get; set; }

    public string BookingStatus { get; set; }

    public DateTime? CancelDate { get; set; }

    public string BookingSource { get; set; }

    public string GuestLoginId { get; set; }

    public string GuestMobileNo { get; set; }

    public string GuestName { get; set; }

    public string BookingGuestname { get; set; }

    public string GuestEmailId { get; set; }

    public string GuestGstno { get; set; }

    public string GuestAddress { get; set; }

    public bool? IsActive { get; set; }

    public string EntryBy { get; set; }

    public DateTime? EntryDate { get; set; }

    public virtual ICollection<B02BookingRoomDetail> B02BookingRoomDetails { get; set; } = new List<B02BookingRoomDetail>();

    public virtual ICollection<B03TransactionDetail> B03TransactionDetails { get; set; } = new List<B03TransactionDetail>();

    public virtual ICollection<B04ChickInDetail> B04ChickInDetails { get; set; } = new List<B04ChickInDetail>();

    public virtual TblHotelMaster Hotel { get; set; }
}