// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hotel.data;

public partial class B02BookingRoomDetail
{
    public long B02BookingRoomId { get; set; }

    public long BookingId { get; set; }

    public string HotelId { get; set; }

    public int CategoryId { get; set; }

    public DateOnly? CheckInDate { get; set; }

    public DateOnly? CheckOutDate { get; set; }

    public int? Days { get; set; }

    public int? NoOfBed { get; set; }

    public int? NoofRooms { get; set; }

    public int? NoofAdults { get; set; }

    public int? NoofChilds { get; set; }

    public int? ExtraBed { get; set; }

    public int? DoubleOccupancy { get; set; }

    public decimal? RoomCharge { get; set; }

    public decimal? DoubleOccupancyCharge { get; set; }

    public decimal? ExtraBedCharge { get; set; }

    public decimal? RoomAmt { get; set; }

    public decimal? DoubleOccupancyAmt { get; set; }

    public decimal? ExtraBedamt { get; set; }

    public decimal? TotalRoomAmt { get; set; }

    public decimal? DiscountPer { get; set; }

    public decimal? DisountAmount { get; set; }

    public decimal? GrossAmount { get; set; }

    public decimal? GstPer { get; set; }

    public decimal? Cgst { get; set; }

    public decimal? Sgst { get; set; }

    public decimal? TotalGst { get; set; }

    public decimal? TotalPayable { get; set; }

    public string Gstnature { get; set; }

    public string BookingStatus { get; set; }

    public int? CancelRoom { get; set; }

    public decimal? RefundPer { get; set; }

    public decimal? RefundAmt { get; set; }

    public DateTime? CancelDate { get; set; }

    public string CancelBy { get; set; }

    public bool? IsActive { get; set; }

    public string EntryBy { get; set; }

    public DateTime? EntryDate { get; set; }

    public virtual B01BookingDetail Booking { get; set; }

    public virtual TblCategoryMaster Category { get; set; }

    public virtual TblHotelMaster Hotel { get; set; }
}