// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hotel.data;

public partial class B03TransactionDetail
{
    public long B03TransactionId { get; set; }

    public long BookingId { get; set; }

    public string PaymentSourse { get; set; }

    public decimal? NetPayable { get; set; }

    public decimal? DiscountAmt { get; set; }

    public decimal? PaidAmount { get; set; }

    public decimal? DueAmount { get; set; }

    public string BillNo { get; set; }

    public string PaymentMode { get; set; }

    public string ResponseUrl { get; set; }

    public string TransactionId { get; set; }

    public DateTime? TransactionDate { get; set; }

    public string Tid { get; set; }

    public string Tmode { get; set; }

    public string Mihpayid { get; set; }

    public string HashResponce { get; set; }

    public string NameOnCard { get; set; }

    public string CardNo { get; set; }

    public string RequestKey { get; set; }

    public bool? IsActive { get; set; }

    public string EntryBy { get; set; }

    public DateTime? EntryDate { get; set; }

    public virtual B01BookingDetail Booking { get; set; }
}