// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hotel.data;

public partial class B04ChickInDetail
{
    public long B04ChickInId { get; set; }

    public long BookingId { get; set; }

    public string HotelId { get; set; }

    public int CategoryId { get; set; }

    public DateTime CheckInDate { get; set; }

    public DateTime CheckOutDate { get; set; }

    public string UpdateStatus { get; set; }

    public DateTime? UpdateDate { get; set; }

    public int NoOfDays { get; set; }

    public string RoomNo { get; set; }

    public string BookingStatus { get; set; }

    public int? NoofAdults { get; set; }

    public int? NoofChilds { get; set; }

    public int? ExtraBed { get; set; }

    public decimal? RoomChargesPerDay { get; set; }

    public decimal? DoubleOccupancyPer { get; set; }

    public decimal? ExtraBedPricePer { get; set; }

    public decimal? TotalRoomCharge { get; set; }

    public decimal? DiscountPer { get; set; }

    public decimal? DisountAmountPer { get; set; }

    public decimal? DisountAmount { get; set; }

    public decimal? GrossAmount { get; set; }

    public decimal? GstPer { get; set; }

    public decimal? GstAmount { get; set; }

    public decimal? Cgst { get; set; }

    public decimal? Sgst { get; set; }

    public decimal? TotalGst { get; set; }

    public decimal? TotalPayable { get; set; }

    public bool? IsActive { get; set; }

    public string EntryBy { get; set; }

    public DateTime? EntryDate { get; set; }

    public virtual B01BookingDetail Booking { get; set; }

    public virtual TblCategoryMaster Category { get; set; }

    public virtual TblHotelMaster Hotel { get; set; }
}