// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hotel.data;

public partial class CityMaster
{
    public int Id { get; set; }

    public int StateId { get; set; }

    public string CityName { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? EntryDate { get; set; }

    public string UnitAbbr { get; set; }
}