// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hotel.data;

public partial class InvoiceNotbl
{
    public long PkInvoiceNoid { get; set; }

    public long? Invoiceno { get; set; }

    public long? RestaurentInvoiceno { get; set; }

    public long? Rbsno { get; set; }

    public long? Billno { get; set; }

    public long? GregNo { get; set; }

    public long? BanquetBookinInvoice { get; set; }

    public long? AgentSrNo { get; set; }
}