// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hotel.data;

public partial class Login
{
    public int UserId { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public int MRoleId { get; set; }

    public string HotelId { get; set; }

    public DateTime? LastLoginDate { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public bool? IsActive { get; set; }

    public string Opt { get; set; }
}