// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hotel.data;

public partial class RateMaster
{
    public int RateId { get; set; }

    public string HotelId { get; set; }

    public int CategoryId { get; set; }

    public decimal PricePerDay { get; set; }

    public decimal? PriceDifference { get; set; }

    public decimal? ExtraBedPercentage { get; set; }

    public DateOnly RateStartDate { get; set; }

    public DateOnly RateEndDate { get; set; }

    public bool? IsActive { get; set; }

    public string EntryBy { get; set; }

    public DateTime? EntryDate { get; set; }

    public virtual TblCategoryMaster Category { get; set; }

    public virtual TblHotelMaster Hotel { get; set; }
}