// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hotel.data;

public partial class TblBedMaster
{
    public int BedId { get; set; }

    public string BedName { get; set; }

    public int? NoofBed { get; set; }

    public virtual ICollection<TblCategoryMaster> TblCategoryMasters { get; set; } = new List<TblCategoryMaster>();
}