// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hotel.data;

public partial class TblCategoryMaster
{
    public int Id { get; set; }

    public string Category { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? EntryDate { get; set; }

    public string Hotelid { get; set; }

    public string MmtcategoryCode { get; set; }

    public string MmthotelCode { get; set; }

    public string IrctcHotelCode { get; set; }

    public string IrctccategoryCode { get; set; }

    public bool? IsOffline { get; set; }

    public int BedId { get; set; }

    public virtual ICollection<B02BookingRoomDetail> B02BookingRoomDetails { get; set; } = new List<B02BookingRoomDetail>();

    public virtual ICollection<B04ChickInDetail> B04ChickInDetails { get; set; } = new List<B04ChickInDetail>();

    public virtual TblBedMaster Bed { get; set; }

    public virtual TblHotelMaster Hotel { get; set; }

    public virtual ICollection<RateMaster> RateMasters { get; set; } = new List<RateMaster>();

    public virtual ICollection<TblRoomDetail> TblRoomDetails { get; set; } = new List<TblRoomDetail>();
}