// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hotel.data;

public partial class TblHotelMaster
{
    public int Id { get; set; }

    public string HotelId { get; set; }

    public string HotelName { get; set; }

    public int? StateId { get; set; }

    public int? CityId { get; set; }

    public bool? IsOffline { get; set; }

    public string Address { get; set; }

    public string ContactNo { get; set; }

    public string Description { get; set; }

    public decimal? Longitude { get; set; }

    public decimal? Latitude { get; set; }

    public DateTime? EntryDate { get; set; }

    public bool? IsActive { get; set; }

    public string EmailId { get; set; }

    public string ImageUrl { get; set; }

    public string Landline { get; set; }

    public string Gstno { get; set; }

    public string HotalCodenew { get; set; }

    public string HotelNameCity { get; set; }

    public int? CounterBillNo { get; set; }

    public string MmtHotelCode { get; set; }

    public string MmtAccessToken { get; set; }

    public long? PatternId { get; set; }

    public string IrctcHotelCode { get; set; }

    public string Fssaino { get; set; }

    public DateOnly? ValidDate { get; set; }

    public string HotelUrlNew { get; set; }

    public string RedirectUrl { get; set; }

    public string AccessToken { get; set; }

    public int? Category { get; set; }

    public int? NoOfRooms { get; set; }

    public virtual ICollection<B01BookingDetail> B01BookingDetails { get; set; } = new List<B01BookingDetail>();

    public virtual ICollection<B02BookingRoomDetail> B02BookingRoomDetails { get; set; } = new List<B02BookingRoomDetail>();

    public virtual ICollection<B04ChickInDetail> B04ChickInDetails { get; set; } = new List<B04ChickInDetail>();

    public virtual ICollection<RateMaster> RateMasters { get; set; } = new List<RateMaster>();

    public virtual ICollection<TblCategoryMaster> TblCategoryMasters { get; set; } = new List<TblCategoryMaster>();

    public virtual ICollection<TblRoomDetail> TblRoomDetails { get; set; } = new List<TblRoomDetail>();
}