// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hotel.data;

public partial class TblRoomDetail
{
    public int RoomId { get; set; }

    public string RoomNo { get; set; }

    public string HotelId { get; set; }

    public int CategoryId { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? EntryDate { get; set; }

    public bool? IsOffLine { get; set; }

    public DateTime? OffLineDate { get; set; }

    public DateOnly? Oldatefrom { get; set; }

    public DateOnly? OldateTo { get; set; }

    public virtual TblCategoryMaster Category { get; set; }

    public virtual TblHotelMaster Hotel { get; set; }
}